# Generated by Django 4.2.2 on 2023-06-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_blogpost_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_start_time', models.TimeField()),
            ],
        ),
    ]
