# Generated by Django 4.2.2 on 2023-06-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
